var mongoose = require("mongoose");   
var rac_post = new mongoose.Schema({  
    Timestamp:Date,
    Username:{type:String,unique: true},
    
    according_to_the_World_Health_Organization_WHO_legally_restricting_abortion_reduces_the_number_of_abortions_that_occur:String,
    in_my_country_abortion_services_are_governed_by_the_law_namely_the_Medical_Termination_of_Pregnancy_MTP_Act:String,

    in_my_country_the_law_was_amended_recently_expanding_access_to_abortion_services_on_therapeutic_eugenic_humanitarian_or_social_grounds:String,
    in_my_country_only_registered_medical_practitioners_RMP_are_authorized_to_perform_abortions:String,
    in_my_country_the_law_opinion_of_only_one_provider_is_required_for_MTP_up_to_20_weeks_of_gestation_and_requirement_of_opinion_of_two_providers_MTP_of_20_24_weeks_of_gestation:String,
    
    in_my_country_in_cases_of_birth_defects_there_is_no_upper_gestation_limit_for_abortion_under_the_MTP_Act:String,
    in_my_country_the_law_requires_a_married_woman_to_obtain_her_husbands_written_consent_before_she_can_undergo_a_termination_of_pregnancy:String,
    in_my_country_the_law_requires_an_adolescent_to_obtain_written_consent_from_both_parents_guardians_before_she_can_undergo_a_termination_of_pregnancy:String,
    in_my_country_the_law_requires_any_woman_seeking_an_abortion_resulting_from_rape_or_incest_to_provide_legal_evidence_of_the_sexual_assault_upto_24_weeks_of_gestation:String,
    in_my_country_safe_abortion_is_available_for_any_woman_married_or_unmarried_including_failure_of_contraception:String,
    where_the_law_permits_abortion_to_prevent_injury_to_the_woman_health_WHO_health_definition_in_the_constitution_can_be_used_a_state_of_complete_physical_mental_and_social_well_being_and_not_merely_the_absenceof_disease_or_infirmity:String,
    most_of_the_women_are_likely_to_have_at_least_one_abortion_by_the_time_they_are_45_years_old:String,
    abortion_is_one_of_the_safest_medical_procedures_when_performed_by_trained_health_care_providers_with_proper_equipment_correct_technique_and_sanitary_standards:String,
    where_effective_contraceptive_methods_are_available_and_widely_used_the_total_abortion_rate_decreases:String,
    if_all_contraceptive_users_become_aware_to_use_methods_perfectly_always_there_would_not_be_any_unintended_or_unwanted_pregnancies:String,

    Enter_the_date_you_actually_attended_the_Training:String,
    Name:String,
    Surname:String,
    Contact_No:String,
 
    // agree/not agree
    The_issue_of_abortion_is_of_importance_to_me:String,
    I_feel_very_conflicted_about_abortion_services:String,
    I_donâte_feel_comfortable_talking_about_abortion_and_family_planning_contraceptive_services_with_my_patientsclients:String,
    I_understand_the_laws_and_regulations_for_the_provision_of_abortion_in_my_country_clearly:String,

    I_am_clear_about_my_personal_values_concerning_abortion:String,
    I_donâte_feel_comfortable_performing_and_or_assisting_an_abortion_procedure_as_per_law:String,
    I_support_the_provision_of_family_planning_and_contraceptive_services:String,
    I_feel_comfortable_talking_with_my_closest_family_members_about_my_involvement_with_abortion:String,
    I_feel_I_can_discuss_stigmatized_issues_including_abortion_comfortably:String,
    I_believe_all_women_should_have_the_choice_to_have_decide_when_they_have_a_baby:String,
    I_can_respectfully_explain_about_abortion_even_if_it_conflicts_with_my_views:String,
    I_know_which_sources_to_turn_to_for_reliable_guidance_on_Sexual_Reproductive_Health_Rights_SRSH_specifically_abortion_and_contraception:String,
    I_am_well_informed_about_national_and_global_goals_and_policies_on_safe_abortion_and_family_planning:String,
    Safe_abortion_services_should_be_given_to_any_women_of_any_age_if_she_chooses_it:String,
    All_women_should_have_access_to_safe_comprehensive_abortion_care:String
  


    
});  
   
const Rac_post_feedback_Schema =mongoose.model('Rac_post',rac_post); 
module.exports = Rac_post_feedback_Schema
